import {
  StyleSheet,
  Text,
  View,
  SafeAreaView,
  Button,
  Alert,
  Image,
  Platform,
} from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  Header: {
    fontSize: 40,
    fontFamily: "monospace",
    marginBottom: "2vh",
  },
  bottomTextLeft: {
    position: "absolute",
    bottom: 0,
    marginBottom: 20,
    marginLeft: 20,
    alignSelf: "flex-start",
    opacity: "30%", 
  },
  album: {
    marginTop: "15%",
    marginBottom: "2%",
    height: "35%",
    width: "35%",
    resizeMode: "contain",
    alignSelf: "center",
    bottom: 0,
  },
  textstyl: {
    fontFamily: "Arial Black",
    fontSize: 80,
    opacity: "40%",
  },
  textstyl2: {
    fontFamily: "monospace",
    fontSize: 15,
    opacity: "70%",
  },
  quotetext: {
    position: "absolute",
    top: "3%",
    left: "10%",
    fontSize: 40,
    fontFamily: "monospace",
    color:"blue",
    alignSelf: "flex-start",
  },
  quotetext2: {
    position: "absolute",
    fontSize: 40,
    top: "5%",
    left: "33%",
    fontFamily: "monospace",
    color:"red",
  },
  quotetext3: {
    position: "absolute",
    fontSize: 40,
    top: "8%",
    left: "50%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext4: {
    position: "absolute",
    fontSize: 40,
    top: "4%",
    left: "57%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext5: {
    position: "absolute",
    fontSize: 40,
    top: "6.9%",
    left: "76%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext6: {
    fontSize: 14,
    top:"10%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext7: {
    position: "absolute",
    fontSize: 40,
    top: "34%",
    left: "4%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext8: {
    position: "absolute",
    fontSize: 40,
    top: "43%",
    left: "28%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext9: {
    position: "absolute",
    fontSize: 40,
    top: "50%",
    left: "72%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext10: {
    position: "absolute",
    fontSize: 40,
    top: "69%",
    left: "4%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext11: {
    position: "absolute",
	  fontSize: 40,
    top: "72%",
    left: "11%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext12: {
    position: "absolute",
	  fontSize: 40,
    top: "74%",
    left: "70%",
    fontFamily: "monospace",
    color:"blue",
  },
  quotetext13: {
    position: "absolute",
	  fontSize: 40,
    top: "90%",
    left: "30%",
	  fontFamily: "monospace",
    color:"blue",
  },
  quotetext14: {
    top: "10.7%",
	  fontFamily: "monospace",
    color:"blue",
  },
  buttonMainpage: {
    marginTop: "3%",
  },
  buttonStyle: {
    fontFamily: "monospace",
    color: "#000000",
  },
  buttonContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  button2Style: {
    alignSelf: "flex-end",
    backgroundColor: "black",
    borderRadius: 5,
    padding: 10,
    margin: 5,
  },
  buttonMiddle: {
    height: 39,
    backgroundColor: "black",
    borderRadius: 5,
    padding: 10,
    margin: 5,
  },
  album_2: {
    ...Platform.select({
      ios: {},
      android: {
        width: "70%",
        height: "20%",
        marginBottom: 20,
        marginTop: 20,
        alignSelf: "center",
        alignContent: "center",
      },
      default: {
        // other platforms, web for example
        width: "35%",
        marginBottom: 20,
        marginTop: 20,
        alignSelf: "center",
        alignContent: "center",
        //resizeMode: 'contain',
      },
    }),
  },
  styleTestJS: {
    fontSize: 30,
    position: "absolute",
  },
  screen2: {
    ...Platform.select({
      ios: {},
      android: {
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        marginTop: 50,
      },
      default: {
        // other platforms, web for example
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        marginHorizontal: 250,
        marginVertical: 200,
      },
    }),
  },
  screen3Container: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    marginBottom: 600,
  },
  screen3: {
    ...Platform.select({
      ios: {},
      android: {
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        marginTop: 50,
      },
      default: {
        //web
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        marginHorizontal: 250,
        marginTop: 200,
        marginBottom: 100,
      },
    }),
  },
  progressBG: {
    width: "100%",
    height: 15,
    backgroundColor: "#C4CDD5",
    //borderRadius: 10,
    position: "fixed",
    bottom: 0,
  },
  progress: {
    width: "50%",
    height: 15,
    backgroundColor: "black",
    //borderRadius: 10,
  },
  label: {
    fontSize: 15,
    fontWeight: "500",
    color: "#005249",
    marginBottom: 20,
    position: "fixed",
    bottom: 0,
  },
  progressBG2: {
    width: "50%",
    height: 15,
    backgroundColor: "#C4CDD5",
    borderRadius: 10,
  },
  progress2: {
    width: "50%",
    height: 15,
    backgroundColor: "black",
    borderRadius: 10,
  },
  label2: {
    fontSize: 15,
    fontWeight: "500",
    color: "#005249",
    marginBottom: 20,
  },
  topAlbum:{
    height: '35vh',
    width: '35vh',
    resizeMode:'contain',
    alignSelf:'center',
    //border: "5px solid #555",
    margin: "3vh",
  },
  testinghard:{
    marginVertical: "17vh",
    marginHorizontal: "20vh",
  },
  bottomMarginForShits: {
    marginVertical: "20vh",
    marginHorizontal: "20vh",
  },
  Header3: {
    fontSize: 40,
    fontFamily: "monospace",
    marginTop: 20
  },

  resultsContainer: {
    paddingTop: 20,
    width: "100%",
    height: "100%",
    flex: 4,
    backgroundColor: "#ffffff",
    alignItems: "center",
  },
  imageContainer: {
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },

  textContainer: {
    flex: 2,
    flexDirection: "column",
    alignContent: "center",
    textAlign: "center",
    padding: "10px",
    alignItems: "center",
    
  },
  textstyl: {
    fontFamily: "Arial Black",
    fontSize: 80,
    opacity: "40%",
  },
  quotetext2: {
    position: "absolute",
    fontSize: 40,
    top: "5%",
    left: "63%",
    fontFamily: "monospace",
  },
});

export { styles };
